version: '3.8'

networks:
  captain:
    external: true
    name: captain-overlay-network
  prom:
    external: true
    name: devops_prom
  ecu: {}

services:
  entre-com-unicamp:
    image: maronato/entre-com-unicamp:5
    networks:
      - ecu
      - captain
      - prom
    env_file: .env
    deploy:
      mode: replicated
      replicas: 1
      labels:
        prometheus-job: "entre-com-unicamp"
        prometheus-port: "9464"
      resources:
        limits:
          memory: 512M
  redis:
    image: redis:6-alpine
    networks:
      - ecu
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 64M