version: "3.8"

networks:
  captain:
    external: true
    name: captain-overlay-network
  prom:
    external: true
    name: devops_prom
  ecu: {}

services:
  entre-com-unicamp:
    image: maronato/entre-com-unicamp:latest
    networks:
      - ecu
      - captain
      - prom
    env_file: .env
    environment:
      DOCKER_SERVICE_ID: "{{.Service.ID}}"
      DOCKER_SERVICE_NAME: "{{.Service.Name}}"
      DOCKER_SERVICE_LABELS: "{{.Service.Labels}}"
      DOCKER_NODE_ID: "{{.Node.ID}}"
      DOCKER_NODE_HOSTNAME: "{{.Node.Hostname}}"
      DOCKER_TASK_ID: "{{.Task.ID}}"
      DOCKER_TASK_NAME: "{{.Task.Name}}"
      DOCKER_TASK_SLOT: "{{.Task.Slot}}"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        prometheus-job: "entre-com-unicamp"
        prometheus-port: "9464"
      resources:
        limits:
          memory: 512M
  redis:
    image: redis:6-alpine
    networks:
      - ecu
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 64M
