version: "3.8"

volumes:
  s3: {}
  postgres: {}

services:
  tempo:
    image: grafana/tempo:1.3.2
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/config.yaml:/etc/tempo.yaml
    ports:
      - 14268:14268 # jaeger ingest

  loki:
    image: grafana/loki:2.4.2
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100" # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1

  prometheus:
    image: prom/prometheus:v2.34.0
    command: ["--config.file=/etc/prometheus.yaml"]
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config.yaml:/etc/prometheus.yaml

  grafana:
    image: grafana/grafana:8.4.4
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3030:3000"

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  minio:
    image: minio/minio:latest
    volumes:
      - s3:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - "MINIO_ROOT_USER=minio_user"
      - "MINIO_ROOT_PASSWORD=minio_password"
      - "MINIO_DOMAIN=localhost:9000"
    command: 'server --console-address ":9001" /data'

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      sh -c '
      sleep 3 &&
      mc config host add s3 http://minio:9000 "minio_user" "minio_password" &&
      mc mb -p s3/development &&
      mc policy set download s3/development &&
      exit 0
      '
