version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 14268:14268
      - 16686:16686

  prometheus:
    image: prom/prometheus:v2.34.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
