version: "3.8"

volumes:
  s3: {}
  postgres: {}

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 14268:14268
      - 16686:16686

  prometheus:
    image: prom/prometheus:v2.34.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  minio:
    image: minio/minio:latest
    volumes:
      - s3:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - "MINIO_ROOT_USER=minio_user"
      - "MINIO_ROOT_PASSWORD=minio_password"
      - "MINIO_DOMAIN=localhost:9000"
    command: 'server --console-address ":9001" /data'

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      sh -c '
      sleep 3 &&
      mc config host add s3 http://minio:9000 "minio_user" "minio_password" &&
      mc mb -p s3/development &&
      mc policy set download s3/development &&
      exit 0
      '
