name: Docker Build/Publish Image
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=version::${GITHUB_RUN_NUMBER}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: maronato/entre-com-unicamp:${{ steps.prepare.outputs.version }},maronato/entre-com-unicamp:latest
          cache-from: type=registry,ref=maronato/entre-com-unicamp:buildcache
          cache-to: type=registry,ref=maronato/entre-com-unicamp:buildcache,mode=max
